"""Create properties table

Revision ID: 8bbfac4cf5da
Revises: 
Create Date: 2025-11-03 06:37:01.359011

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8bbfac4cf5da"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "properties",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("city", sa.String(length=50), nullable=False, comment="縣市"),
        sa.Column("district", sa.String(length=50), nullable=False, comment="鄉鎮市區"),
        sa.Column("land_location", sa.Text(), nullable=True, comment="土地位置"),
        sa.Column(
            "land_section",
            sa.String(length=255),
            nullable=True,
            comment="土地區段位置或建物區段門牌",
        ),
        sa.Column(
            "transaction_date",
            sa.String(length=10),
            nullable=False,
            comment="交易年月日 (ROC format)",
        ),
        sa.Column(
            "transaction_pen_number",
            sa.String(length=255),
            nullable=True,
            comment="交易筆棟數",
        ),
        sa.Column(
            "land_area_sqm",
            sa.Numeric(precision=15, scale=2),
            nullable=True,
            comment="土地移轉總面積平方公尺",
        ),
        sa.Column(
            "urban_land_use_type",
            sa.String(length=100),
            nullable=True,
            comment="都市土地使用分區",
        ),
        sa.Column(
            "non_urban_land_use_type",
            sa.String(length=100),
            nullable=True,
            comment="非都市土地使用分區",
        ),
        sa.Column(
            "non_urban_land_use_category",
            sa.String(length=100),
            nullable=True,
            comment="非都市土地使用編定",
        ),
        sa.Column(
            "transaction_purpose",
            sa.String(length=100),
            nullable=True,
            comment="交易目的",
        ),
        sa.Column("main_use", sa.String(length=100), nullable=True, comment="主要用途"),
        sa.Column(
            "main_building_materials",
            sa.String(length=100),
            nullable=True,
            comment="主要建材",
        ),
        sa.Column(
            "construction_complete_date",
            sa.String(length=10),
            nullable=True,
            comment="建築完成年月 (ROC format)",
        ),
        sa.Column(
            "building_area_sqm",
            sa.Numeric(precision=15, scale=2),
            nullable=True,
            comment="建物移轉總面積平方公尺",
        ),
        sa.Column("building_rooms", sa.Integer(), nullable=True, comment="建物現況格局-房"),
        sa.Column("building_halls", sa.Integer(), nullable=True, comment="建物現況格局-廳"),
        sa.Column(
            "building_bathrooms", sa.Integer(), nullable=True, comment="建物現況格局-衛"
        ),
        sa.Column(
            "building_compartments",
            sa.Boolean(),
            nullable=True,
            comment="建物現況格局-隔間 (有/無)",
        ),
        sa.Column("has_management", sa.Boolean(), nullable=True, comment="有無管理組織"),
        sa.Column("total_floor_number", sa.Integer(), nullable=True, comment="總樓層數"),
        sa.Column(
            "building_floor_number",
            sa.String(length=50),
            nullable=True,
            comment="建物移轉層次",
        ),
        sa.Column(
            "total_price_ntd",
            sa.Numeric(precision=20, scale=2),
            nullable=False,
            comment="總價元",
        ),
        sa.Column(
            "unit_price_ntd",
            sa.Numeric(precision=15, scale=2),
            nullable=True,
            comment="單價元平方公尺",
        ),
        sa.Column(
            "parking_area_sqm",
            sa.Numeric(precision=15, scale=2),
            nullable=True,
            comment="車位移轉總面積平方公尺",
        ),
        sa.Column(
            "parking_price_ntd",
            sa.Numeric(precision=20, scale=2),
            nullable=True,
            comment="車位總價元",
        ),
        sa.Column("remarks", sa.Text(), nullable=True, comment="備註"),
        sa.Column("serial_number", sa.String(length=100), nullable=True, comment="編號"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_area_range", "properties", ["building_area_sqm"], unique=False)
    op.create_index(
        "idx_city_district", "properties", ["city", "district"], unique=False
    )
    op.create_index("idx_price_range", "properties", ["total_price_ntd"], unique=False)
    op.create_index(
        "idx_transaction_date_city",
        "properties",
        ["transaction_date", "city"],
        unique=False,
    )
    op.create_index(op.f("ix_properties_city"), "properties", ["city"], unique=False)
    op.create_index(
        op.f("ix_properties_district"), "properties", ["district"], unique=False
    )
    op.create_index(op.f("ix_properties_id"), "properties", ["id"], unique=False)
    op.create_index(
        op.f("ix_properties_transaction_date"),
        "properties",
        ["transaction_date"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_properties_transaction_date"), table_name="properties")
    op.drop_index(op.f("ix_properties_id"), table_name="properties")
    op.drop_index(op.f("ix_properties_district"), table_name="properties")
    op.drop_index(op.f("ix_properties_city"), table_name="properties")
    op.drop_index("idx_transaction_date_city", table_name="properties")
    op.drop_index("idx_price_range", table_name="properties")
    op.drop_index("idx_city_district", table_name="properties")
    op.drop_index("idx_area_range", table_name="properties")
    op.drop_table("properties")
    # ### end Alembic commands ###
