"""add_missing_fields

Revision ID: fd66a6c37a17
Revises: 3b45be381d0e
Create Date: 2025-11-03 11:13:22.172419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "fd66a6c37a17"
down_revision: Union[str, None] = "3b45be381d0e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "properties",
        "land_section",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=255),
        comment="土地區段位置或建物區段門牌",
        existing_nullable=True,
    )
    op.alter_column(
        "properties",
        "urban_land_use_type",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=500),
        comment="都市土地使用分區",
        existing_nullable=True,
    )
    op.alter_column(
        "properties",
        "non_urban_land_use_type",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=100),
        type_=sa.String(length=500),
        comment="非都市土地使用分區",
        existing_nullable=True,
    )
    op.alter_column(
        "properties",
        "non_urban_land_use_category",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=100),
        type_=sa.String(length=500),
        comment="非都市土地使用編定",
        existing_nullable=True,
    )
    op.alter_column(
        "properties",
        "transaction_purpose",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=100),
        type_=sa.String(length=500),
        existing_comment="交易目的",
        existing_nullable=True,
    )
    op.create_index(
        op.f("ix_properties_building_type"),
        "properties",
        ["building_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_properties_has_elevator"), "properties", ["has_elevator"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_properties_has_elevator"), table_name="properties")
    op.drop_index(op.f("ix_properties_building_type"), table_name="properties")
    op.alter_column(
        "properties",
        "transaction_purpose",
        existing_type=sa.String(length=500),
        type_=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=100),
        existing_comment="交易目的",
        existing_nullable=True,
    )
    op.alter_column(
        "properties",
        "non_urban_land_use_category",
        existing_type=sa.String(length=500),
        type_=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=100),
        comment=None,
        existing_comment="非都市土地使用編定",
        existing_nullable=True,
    )
    op.alter_column(
        "properties",
        "non_urban_land_use_type",
        existing_type=sa.String(length=500),
        type_=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=100),
        comment=None,
        existing_comment="非都市土地使用分區",
        existing_nullable=True,
    )
    op.alter_column(
        "properties",
        "urban_land_use_type",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=500),
        comment=None,
        existing_comment="都市土地使用分區",
        existing_nullable=True,
    )
    op.alter_column(
        "properties",
        "land_section",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=255),
        comment=None,
        existing_comment="土地區段位置或建物區段門牌",
        existing_nullable=True,
    )
    # ### end Alembic commands ###
